M48
; DRILL file {KiCad 8.0.1} date 2024-06-17T12:01:40-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-17T12:01:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X4.9213Y-5.264
X4.9213Y-5.3624
X5.1181Y-5.0671
X5.315Y-5.264
X5.315Y-5.3624
M30
